services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: nuxt-note-mongodb
    restart: always
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27017"]
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongodb/init:/docker-entrypoint-initdb.d
    networks:
      - nuxt-network
    healthcheck:
      test: test $$(echo "rs.initiate().ok || rs.status().ok" | mongosh --port 27017 --quiet) -eq 1
      interval: 10s
      start_period: 30s

  # Mongo Express (MongoDB Admin Interface)
  mongo-express:
    image: mongo-express:1.0.2
    container_name: nuxt-note-mongo-express
    restart: always
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongodb:27017/?replicaSet=rs0
      ME_CONFIG_BASICAUTH: false
    ports:
      - "1433:8081"
    depends_on:
      - mongodb
    networks:
      - nuxt-network

  # Nuxt Application
  # nuxt-app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: nuxt-note-app
  #   restart: always
  #   environment:
  #     - NODE_ENV=development
  #     - DATABASE_URL=mongodb://root:rootpassword@mongodb:27017/nuxt_notes?authSource=admin
  #     - JWT_SECRET=your-super-secret-jwt-key-change-this-in-production
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - mongodb
  #   volumes:
  #     - .:/app
  #     - /app/node_modules
  #   networks:
  #     - nuxt-network

volumes:
  mongodb_data:

networks:
  nuxt-network:
    driver: bridge
